<?php

$templatesMorning = [
    ['title' => 'Risposta iniziale', 'message' => "Buongiorno 👋 Sono Andrea di Stuart.\nPer poterle indicare subito la soluzione più adatta e un prezzo orientativo, mi scriva semplicemente:\n- per quale utilizzo sono destinate (ad esempio: evento, azienda, squadra sportiva, merchandising...)\n- la quantità indicativa\n- come immagina la personalizzazione (ad esempio: logo sul petto, stampa fronte e retro, nomi e numeri...)\nIn base a queste informazioni le consiglierò il prodotto più adatto al suo progetto e le comunicherò il relativo prezzo.\nSe la soluzione sarà in linea con le sue aspettative, realizzeremo gratuitamente anche un'anteprima grafica del progetto e una proposta completa."],
    ['title' => 'Follow-up 1 risposta automatica', 'message' => "Buongiorno!\nLe scrivo solo per sapere se è ancora interessato al suo progetto.\nMi bastano una breve descrizione dell'utilizzo, la quantità e la personalizzazione desiderata per poterle indicare subito la soluzione più adatta e il relativo costo.\nRimango a disposizione"],
    ['title' => 'Comunicazione del prezzo', 'message' => "Perfetto, grazie!\nPer il suo progetto ci sono diverse possibilità in base alla qualità del prodotto.\n\nEconomic -> € ... + IVA cad.\nIdeale per eventi e utilizzi occasionali.\n\nBasic -> € ... + IVA cad.\nIl miglior equilibrio tra qualità, vestibilità e durata.\n\nPremium -> € ... + IVA cad.\nPensata per merchandising e utilizzi continuativi.\n\nPer quello che deve realizzare, le consiglierei la Basic.\nSe il prezzo è in linea con quello che aveva in mente, preparo gratuitamente anche un'anteprima grafica del progetto e una proposta completa."],
    ['title' => 'Follow-up 2 no risposta dopo il prezzo', 'message' => "Buongiorno!\nVolevo sapere se ha avuto modo di valutare la proposta economica che le ho inviato.\nSe desidera possiamo confrontarci anche su soluzioni diverse per trovare quella più adatta alle sue esigenze.\nRimango a disposizione"],
    ['title' => 'Prezzo accettato', 'message' => "Perfetto!\nProcedo con la preparazione dell'anteprima grafica e della proposta completa.\nSe possibile, mi invii il logo in alta qualità (preferibilmente vettoriale) e mi indichi il colore del prodotto che desidera.\nNon appena saranno pronti, glieli invierò così potrà valutarli con calma prima della conferma dell'ordine."],
    ['title' => 'Prezzo troppo alto o vuole modificare', 'message' => "Nessun problema.\nPossiamo rivedere insieme la proposta scegliendo un prodotto diverso oppure modificando la personalizzazione, così da trovare la soluzione più adatta alle sue esigenze.\nMi dica pure cosa vorrebbe cambiare e sarò felice di consigliarla."],
    ['title' => 'Invio anteprima grafica', 'message' => "Buongiorno!\nCome promesso, le invio l'anteprima grafica del suo progetto.\nLa utilizzi per valutare il risultato generale: se desidera apportare modifiche o provare soluzioni diverse, sarò felice di aggiornarla fino a trovare quella che la soddisfa pienamente."],
    ['title' => 'Follow-up 3 dopo anteprima', 'message' => "Buongiorno!\nLe scrivo per sapere se ha avuto modo di visionare l'anteprima grafica e la proposta che le ho inviato.\nSe desidera apportare modifiche oppure ha qualsiasi dubbio, sarò felice di aiutarla.\nRimango a disposizione"],
    ['title' => 'Invio proposta completa', 'message' => "Perfetto!\nIn allegato trova la proposta completa con il riepilogo della fornitura, i prezzi e tutte le informazioni relative al suo progetto.\nSe è tutto di suo gradimento, potremo procedere con la conferma dell'ordine."],
    ['title' => 'Invio link pagamento', 'message' => "Perfetto, possiamo procedere.\nDi seguito trova il link per confermare l'ordine in modo semplice e sicuro.\nNon appena riceveremo la conferma del pagamento, avvieremo la produzione e le comunicheremo la data di consegna prevista.\nRimango a disposizione per qualsiasi necessità."],
    ['title' => 'Follow-up 4 dopo link', 'message' => "Buongiorno!\nLe scrivo perché il suo progetto è pronto per essere confermato.\nSe desidera procedere, il link di pagamento che le ho inviato è ancora valido.\nPer qualsiasi domanda o chiarimento resto a sua disposizione."],
    ['title' => 'Richiesta recensione', 'message' => "Buongiorno!\nSpero che i prodotti siano arrivati e che siano di suo gradimento.\nSe ha qualche minuto, mi farebbe molto piacere ricevere una sua recensione. È un aiuto prezioso per far conoscere Stuart a nuovi clienti.\nPuò lasciarla qui:\n[link recensione]\nLa ringrazio davvero per la fiducia e spero di poter collaborare nuovamente con lei."],
];


$templatesEvening = [
    ['title' => 'Risposta iniziale', 'message' => "Buonasera 👋 Sono Andrea di Stuart.\nPer poterle indicare subito la soluzione più adatta e un prezzo orientativo, mi scriva semplicemente:\n- per quale utilizzo sono destinate (ad esempio: evento, azienda, squadra sportiva, merchandising...)\n- la quantità indicativa\n- come immagina la personalizzazione (ad esempio: logo sul petto, stampa fronte e retro, nomi e numeri...)\nIn base a queste informazioni le consiglierò il prodotto più adatto al suo progetto e le comunicherò il relativo prezzo.\nSe la soluzione sarà in linea con le sue aspettative, realizzeremo gratuitamente anche un'anteprima grafica del progetto e una proposta completa."],
    ['title' => 'Follow-up 1 risposta automatica', 'message' => "Buonasera!\nLe scrivo solo per sapere se è ancora interessato al suo progetto.\nMi bastano una breve descrizione dell'utilizzo, la quantità e la personalizzazione desiderata per poterle indicare subito la soluzione più adatta e il relativo costo.\nRimango a disposizione"],
    ['title' => 'Comunicazione del prezzo', 'message' => "Perfetto, grazie!\nPer il suo progetto ci sono diverse possibilità in base alla qualità del prodotto.\n\nEconomic -> € ... + IVA cad.\nIdeale per eventi e utilizzi occasionali.\n\nBasic -> € ... + IVA cad.\nIl miglior equilibrio tra qualità, vestibilità e durata.\n\nPremium -> € ... + IVA cad.\nPensata per merchandising e utilizzi continuativi.\n\nPer quello che deve realizzare, le consiglierei la Basic.\nSe il prezzo è in linea con quello che aveva in mente, preparo gratuitamente anche un'anteprima grafica del progetto e una proposta completa."],
    ['title' => 'Follow-up 2 no risposta dopo il prezzo', 'message' => "Buonasera!\nVolevo sapere se ha avuto modo di valutare la proposta economica che le ho inviato.\nSe desidera possiamo confrontarci anche su soluzioni diverse per trovare quella più adatta alle sue esigenze.\nRimango a disposizione"],
    ['title' => 'Prezzo accettato', 'message' => "Perfetto!\nProcedo con la preparazione dell'anteprima grafica e della proposta completa.\nSe possibile, mi invii il logo in alta qualità (preferibilmente vettoriale) e mi indichi il colore del prodotto che desidera.\nNon appena saranno pronti, glieli invierò così potrà valutarli con calma prima della conferma dell'ordine."],
    ['title' => 'Prezzo troppo alto o vuole modificare', 'message' => "Nessun problema.\nPossiamo rivedere insieme la proposta scegliendo un prodotto diverso oppure modificando la personalizzazione, così da trovare la soluzione più adatta alle sue esigenze.\nMi dica pure cosa vorrebbe cambiare e sarò felice di consigliarla."],
    ['title' => 'Invio anteprima grafica', 'message' => "Buonasera!\nCome promesso, le invio l'anteprima grafica del suo progetto.\nLa utilizzi per valutare il risultato generale: se desidera apportare modifiche o provare soluzioni diverse, sarò felice di aggiornarla fino a trovare quella che la soddisfa pienamente."],
    ['title' => 'Follow-up 3 dopo anteprima', 'message' => "Buonasera!\nLe scrivo per sapere se ha avuto modo di visionare l'anteprima grafica e la proposta che le ho inviato.\nSe desidera apportare modifiche oppure ha qualsiasi dubbio, sarò felice di aiutarla.\nRimango a disposizione"],
    ['title' => 'Invio proposta completa', 'message' => "Perfetto!\nIn allegato trova la proposta completa con il riepilogo della fornitura, i prezzi e tutte le informazioni relative al suo progetto.\nSe è tutto di suo gradimento, potremo procedere con la conferma dell'ordine."],
    ['title' => 'Invio link pagamento', 'message' => "Perfetto, possiamo procedere.\nDi seguito trova il link per confermare l'ordine in modo semplice e sicuro.\nNon appena riceveremo la conferma del pagamento, avvieremo la produzione e le comunicheremo la data di consegna prevista.\nRimango a disposizione per qualsiasi necessità."],
    ['title' => 'Follow-up 4 dopo link', 'message' => "Buonasera!\nLe scrivo perché il suo progetto è pronto per essere confermato.\nSe desidera procedere, il link di pagamento che le ho inviato è ancora valido.\nPer qualsiasi domanda o chiarimento resto a sua disposizione."],
    ['title' => 'Richiesta recensione', 'message' => "Buonasera!\nSpero che i prodotti siano arrivati e che siano di suo gradimento.\nSe ha qualche minuto, mi farebbe molto piacere ricevere una sua recensione. È un aiuto prezioso per far conoscere Stuart a nuovi clienti.\nPuò lasciarla qui:\n[link recensione]\nLa ringrazio davvero per la fiducia e spero di poter collaborare nuovamente con lei."],
];

return [
    'morning' => $templatesMorning,
    'evening' => $templatesEvening,
];
