<?php

$priceCommunication = "Perfetto, grazie!\n\nPer il suo progetto ci sono diverse soluzioni in base alla qualità del capo. I prezzi si riferiscono a 40 pezzi con personalizzazione lato cuore e retro inclusa. Per quantità superiori il costo unitario diminuisce.\n\nEconomic - EUR 5,49 / pz + IVA\n100% cotone. Ideale per eventi e utilizzi occasionali.\nTotale 40 pz: EUR 219,60 + IVA - EUR 267,91 IVA inclusa\n\nBasic - EUR 6,89 / pz + IVA\n100% cotone. Il miglior equilibrio tra qualità, vestibilità e durata.\nTotale 40 pz: EUR 275,60 + IVA - EUR 336,23 IVA inclusa\n\nPremium - EUR 9,85 / pz + IVA\n100% cotone biologico. Pensata per merchandising e utilizzi continuativi.\nTotale 40 pz: EUR 394,00 + IVA - EUR 480,68 IVA inclusa\n\nI prezzi comprendono le personalizzazioni indicate. La consegna è gratuita da EUR 250,00; altrimenti il costo è di EUR 9,90.\n\nTempi: spedizione entro 6 giorni lavorativi dalla conferma dell'ordine, con consegna normalmente in 24/48 ore lavorative dalla spedizione.\n\nSe desidera confrontare altre quantità o configurazioni può calcolare direttamente il prezzo qui:\nCalcola il tuo prezzo -> https://stuart-company.com/#calcolatore-prezzo\n\nSe il prezzo è in linea con quello che aveva in mente, preparerò gratuitamente il mockup del capo scelto e le invierò anche la relativa scheda prodotto, così potrà valutarne caratteristiche, colori e taglie senza alcun impegno.\n\nSe preferisce parlarne direttamente, può chiamarmi o scrivermi al 345 8007031 e sarò felice di aiutarla.";

$templatesMorning = [
    ['title' => 'Risposta iniziale', 'message' => "Buongiorno! 👋 Sono Andrea di Stuart.\n\nPer poterle consigliare il capo più adatto e comunicarle subito il prezzo, mi scriva semplicemente:\n\n- la quantità indicativa (ordine minimo 15 pezzi)\n- come immagina la personalizzazione (ad esempio: logo sul cuore, stampa fronte e retro, nomi e numeri...)\n- per quale utilizzo sono destinati i capi (ad esempio: azienda, evento, squadra sportiva, merchandising...)\n\nIn base a queste informazioni le consiglierò il prodotto più adatto e le comunicherò subito il prezzo.\n\nSe il prezzo sarà in linea con le sue aspettative, preparerò gratuitamente il mockup del capo scelto."],
    ['title' => 'Risposta iniziale calcolatore', 'message' => "Buongiorno! 👋 Sono Andrea di Stuart.\n\nPerfetto, ho ricevuto la sua richiesta.\n\nPer prepararle gratuitamente l'anteprima grafica mi invii semplicemente:\n\n- il logo o la grafica da utilizzare\n- il colore della t-shirt che preferisce\n\nAppena ricevo il materiale preparo il mockup e glielo invio insieme alla scheda prodotto, così potrà vedere il risultato prima di confermare l'ordine."],
    ['title' => 'Risposta iniziale anteprima live', 'message' => "Buongiorno! 👋 Sono Andrea di Stuart.\n\nPerfetto, ho ricevuto il suo progetto e le grafiche caricate.\n\nL'anteprima visualizzata sul sito serve per darle una prima idea del risultato. Prima di procedere controlleremo noi i file e prepareremo il mockup definitivo, verificando dove necessario:\n\n- rimozione di eventuali sfondi\n- proporzioni e dimensioni della grafica\n- posizionamento sul capo\n- qualità e correttezza dei file\n- eventuali piccole ottimizzazioni grafiche possibili\n\nLe invierò quindi il mockup definitivo insieme alla scheda prodotto, così potrà verificare caratteristiche, colori e vestibilità e comunicarci successivamente le taglie.\n\nSolo dopo la sua approvazione procederemo con la conferma dell'ordine."],
    ['title' => 'Follow-up 1 risposta automatica', 'message' => "Buongiorno!\nLe scrivo solo per sapere se è ancora interessato al suo progetto.\nMi bastano una breve descrizione dell'utilizzo, la quantità e la personalizzazione desiderata per poterle indicare subito la soluzione più adatta e il relativo costo.\nRimango a disposizione"],
    ['title' => 'Comunicazione del prezzo', 'message' => $priceCommunication],
    ['title' => 'Follow-up 2 no risposta dopo il prezzo', 'message' => "Buongiorno!\nVolevo sapere se ha avuto modo di valutare la proposta economica che le ho inviato.\nSe desidera possiamo confrontarci anche su soluzioni diverse per trovare quella più adatta alle sue esigenze.\nRimango a disposizione"],
    ['title' => 'Prezzo accettato', 'message' => "Perfetto!\nProcedo con la preparazione dell'anteprima grafica e della proposta completa.\nSe possibile, mi invii il logo in alta qualità (preferibilmente vettoriale) e mi indichi il colore del prodotto che desidera.\nNon appena saranno pronti, glieli invierò così potrà valutarli con calma prima della conferma dell'ordine."],
    ['title' => 'Prezzo troppo alto o vuole modificare', 'message' => "Nessun problema.\nPossiamo rivedere insieme la proposta scegliendo un prodotto diverso oppure modificando la personalizzazione, così da trovare la soluzione più adatta alle sue esigenze.\nMi dica pure cosa vorrebbe cambiare e sarò felice di consigliarla."],
    ['title' => 'Invio anteprima grafica', 'message' => "Buongiorno!\nCome promesso, le invio l'anteprima grafica del suo progetto.\nLa utilizzi per valutare il risultato generale: se desidera apportare modifiche o provare soluzioni diverse, sarò felice di aggiornarla fino a trovare quella che la soddisfa pienamente."],
    ['title' => 'Follow-up 3 dopo anteprima', 'message' => "Buongiorno!\nLe scrivo per sapere se ha avuto modo di visionare l'anteprima grafica e la proposta che le ho inviato.\nSe desidera apportare modifiche oppure ha qualsiasi dubbio, sarò felice di aiutarla.\nRimango a disposizione"],
    ['title' => 'Invio proposta completa', 'message' => "Perfetto!\nIn allegato trova la proposta completa con il riepilogo della fornitura, i prezzi e tutte le informazioni relative al suo progetto.\nSe è tutto di suo gradimento, potremo procedere con la conferma dell'ordine."],
    ['title' => 'Invio link pagamento', 'message' => "Perfetto, possiamo procedere.\nDi seguito trova il link per confermare l'ordine in modo semplice e sicuro.\nNon appena riceveremo la conferma del pagamento, avvieremo la produzione e le comunicheremo la data di consegna prevista.\nRimango a disposizione per qualsiasi necessità."],
    ['title' => 'Follow-up 4 dopo link', 'message' => "Buongiorno!\nLe scrivo perché il suo progetto è pronto per essere confermato.\nSe desidera procedere, il link di pagamento che le ho inviato è ancora valido.\nPer qualsiasi domanda o chiarimento resto a sua disposizione."],
    ['title' => 'Richiesta recensione', 'message' => "Buongiorno!\nSpero che i prodotti siano arrivati e che siano di suo gradimento.\nSe ha qualche minuto, mi farebbe molto piacere ricevere una sua recensione. È un aiuto prezioso per far conoscere Stuart a nuovi clienti.\nPuò lasciarla qui:\n[link recensione]\nLa ringrazio davvero per la fiducia e spero di poter collaborare nuovamente con lei."],
];


$templatesEvening = [
    ['title' => 'Risposta iniziale', 'message' => "Buonasera! 👋 Sono Andrea di Stuart.\n\nPer poterle consigliare il capo più adatto e comunicarle subito il prezzo, mi scriva semplicemente:\n\n- la quantità indicativa (ordine minimo 15 pezzi)\n- come immagina la personalizzazione (ad esempio: logo sul cuore, stampa fronte e retro, nomi e numeri...)\n- per quale utilizzo sono destinati i capi (ad esempio: azienda, evento, squadra sportiva, merchandising...)\n\nIn base a queste informazioni le consiglierò il prodotto più adatto e le comunicherò subito il prezzo.\n\nSe il prezzo sarà in linea con le sue aspettative, preparerò gratuitamente il mockup del capo scelto."],
    ['title' => 'Risposta iniziale calcolatore', 'message' => "Buonasera! 👋 Sono Andrea di Stuart.\n\nPerfetto, ho ricevuto la sua richiesta.\n\nPer prepararle gratuitamente l'anteprima grafica mi invii semplicemente:\n\n- il logo o la grafica da utilizzare\n- il colore della t-shirt che preferisce\n\nAppena ricevo il materiale preparo il mockup e glielo invio insieme alla scheda prodotto, così potrà vedere il risultato prima di confermare l'ordine."],
    ['title' => 'Risposta iniziale anteprima live', 'message' => "Buonasera! 👋 Sono Andrea di Stuart.\n\nPerfetto, ho ricevuto il suo progetto e le grafiche caricate.\n\nL'anteprima visualizzata sul sito serve per darle una prima idea del risultato. Prima di procedere controlleremo noi i file e prepareremo il mockup definitivo, verificando dove necessario:\n\n- rimozione di eventuali sfondi\n- proporzioni e dimensioni della grafica\n- posizionamento sul capo\n- qualità e correttezza dei file\n- eventuali piccole ottimizzazioni grafiche possibili\n\nLe invierò quindi il mockup definitivo insieme alla scheda prodotto, così potrà verificare caratteristiche, colori e vestibilità e comunicarci successivamente le taglie.\n\nSolo dopo la sua approvazione procederemo con la conferma dell'ordine."],
    ['title' => 'Follow-up 1 risposta automatica', 'message' => "Buonasera!\nLe scrivo solo per sapere se è ancora interessato al suo progetto.\nMi bastano una breve descrizione dell'utilizzo, la quantità e la personalizzazione desiderata per poterle indicare subito la soluzione più adatta e il relativo costo.\nRimango a disposizione"],
    ['title' => 'Comunicazione del prezzo', 'message' => $priceCommunication],
    ['title' => 'Follow-up 2 no risposta dopo il prezzo', 'message' => "Buonasera!\nVolevo sapere se ha avuto modo di valutare la proposta economica che le ho inviato.\nSe desidera possiamo confrontarci anche su soluzioni diverse per trovare quella più adatta alle sue esigenze.\nRimango a disposizione"],
    ['title' => 'Prezzo accettato', 'message' => "Perfetto!\nProcedo con la preparazione dell'anteprima grafica e della proposta completa.\nSe possibile, mi invii il logo in alta qualità (preferibilmente vettoriale) e mi indichi il colore del prodotto che desidera.\nNon appena saranno pronti, glieli invierò così potrà valutarli con calma prima della conferma dell'ordine."],
    ['title' => 'Prezzo troppo alto o vuole modificare', 'message' => "Nessun problema.\nPossiamo rivedere insieme la proposta scegliendo un prodotto diverso oppure modificando la personalizzazione, così da trovare la soluzione più adatta alle sue esigenze.\nMi dica pure cosa vorrebbe cambiare e sarò felice di consigliarla."],
    ['title' => 'Invio anteprima grafica', 'message' => "Buonasera!\nCome promesso, le invio l'anteprima grafica del suo progetto.\nLa utilizzi per valutare il risultato generale: se desidera apportare modifiche o provare soluzioni diverse, sarò felice di aggiornarla fino a trovare quella che la soddisfa pienamente."],
    ['title' => 'Follow-up 3 dopo anteprima', 'message' => "Buonasera!\nLe scrivo per sapere se ha avuto modo di visionare l'anteprima grafica e la proposta che le ho inviato.\nSe desidera apportare modifiche oppure ha qualsiasi dubbio, sarò felice di aiutarla.\nRimango a disposizione"],
    ['title' => 'Invio proposta completa', 'message' => "Perfetto!\nIn allegato trova la proposta completa con il riepilogo della fornitura, i prezzi e tutte le informazioni relative al suo progetto.\nSe è tutto di suo gradimento, potremo procedere con la conferma dell'ordine."],
    ['title' => 'Invio link pagamento', 'message' => "Perfetto, possiamo procedere.\nDi seguito trova il link per confermare l'ordine in modo semplice e sicuro.\nNon appena riceveremo la conferma del pagamento, avvieremo la produzione e le comunicheremo la data di consegna prevista.\nRimango a disposizione per qualsiasi necessità."],
    ['title' => 'Follow-up 4 dopo link', 'message' => "Buonasera!\nLe scrivo perché il suo progetto è pronto per essere confermato.\nSe desidera procedere, il link di pagamento che le ho inviato è ancora valido.\nPer qualsiasi domanda o chiarimento resto a sua disposizione."],
    ['title' => 'Richiesta recensione', 'message' => "Buonasera!\nSpero che i prodotti siano arrivati e che siano di suo gradimento.\nSe ha qualche minuto, mi farebbe molto piacere ricevere una sua recensione. È un aiuto prezioso per far conoscere Stuart a nuovi clienti.\nPuò lasciarla qui:\n[link recensione]\nLa ringrazio davvero per la fiducia e spero di poter collaborare nuovamente con lei."],
];

return [
    'morning' => $templatesMorning,
    'evening' => $templatesEvening,
];
